config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'api_test' => 'api_test#test'

  root 'static_pages#index'

  resources :users
  resources :articles
  resources :videos

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'adminpanel' => 'adminpanel#index'
  post 'adminpanel' => 'adminpanel#new_resource'

  # subscribe route
  post 'subscribe' => 'static_pages#subscribe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'will_paginate/array'

  def index
    @articles = Article.order(created_at: :desc).paginate(:per_page => 9, :page => params[:page])
    @list_articles = Article.all.order('created_at DESC')
    @technical_articles = Article.where("article_type = 'programming' OR article_type = 'technical' OR article_type = 'ruby' OR article_type = 'web_development'
                                        OR article_type = 'linux' OR article_type = 'database' OR article_type = 'devops' OR article_type = 'windows'").order('created_at DESC')
    @personal_development_articles = Article.where("article_type = 'soft_skills'").order('created_at DESC')
    @videos = Video.order(created_at: :desc).paginate(:per_page => 9, :page => params[:page])
  end

  def subscribe
    @subscribe = Subscribe.new(subscribe_params)
    if (!@subscribe.nil? && @subscribe.name != "" && @subscribe.email != "") && @subscribe.save
      flash[:success] = "You have subscribed successfully!"
      redirect_to '/'
    else
      flash[:danger] = "Error, Not Subscribed" + " " + @subscribe.errors.messages.to_s
      redirect_to '/'
    end
  end

  private
  def subscribe_params
    params.require(:subscribe).permit(:name, :email)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<button id="arrow" class="p2">
    <span>▾</span>
</button>
<%= render 'layouts/navbar' %>
<div class="videoContainer">
  <%= video_tag("movie5.mp4", :autoplay => true, :loop => true, id: "myVideo") %>
</div>
<div class="section">
  <div class=row>
    <div class="center well">
      <ul>
        <li class="profile-a"><a href="#">code | drink coffee | code some more</a></li>
      </ul>
    </div>
  </div>
  <div class="row" id="page2">
    <div class="container">
    <div class="col m4" id="topics-list">
      <h5>CONTENT</h5>
        <div class="topics-container">
          <ul class="collapsible popout" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">
                <i class="material-icons">keyboard_arrow_down</i>
                TECHNICAL
              </div>
              <div class="collapsible-body">
                <ul>
                  <% @technical_articles.each do |article| %>
                    <li>
                      <%= link_to "#{article.title}", article_path(article), class: "expandable-article-title" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li>
              <div class="collapsible-header">
                <i class="material-icons">keyboard_arrow_down</i>
                PERSONAL DEVELOPMENT
              </div>
              <div class="collapsible-body">
                <ul>
                  <% @personal_development_articles.each do |article| %>
                    <li>
                      <%= link_to "#{article.title}", article_path(article), class: "expandable-article-title" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li>
              <div class="collapsible-header">
                <i class="material-icons">keyboard_arrow_down</i>
                ARTICLES
              </div>
              <div class="collapsible-body">
                <ul>
                  <% @list_articles.each do |article| %>
                    <li>
                      <%= link_to "#{article.title}", article_path(article), class: "expandable-article-title" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li>
              <div class="collapsible-header">
                <i class="material-icons">keyboard_arrow_down</i>
                VIDEOS
              </div>
              <div class="collapsible-body">
                <ul>
                  <% @videos.each do |video| %>
                    <li>
                      <%= link_to "#{video.title}", article_path(video), class: "expandable-article-title" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li>
              <div class="collapsible-header">
                <i class="material-icons">keyboard_arrow_down</i>
                RESOURCES
              </div>
              <div class="collapsible-body">
                <ul>
                  <li>Coming Soon!</li>
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col m8" id="main-page-feed-column">
          <div class="row">
            <div class="col s12">
              <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#test1">Articles</a></li>
                <li class="tab col s3"><a href="#test2">Videos</a></li>
              </ul>
            </div>
            <div id="articles">
              <div id="test1" class="col s12">
                <%= render 'layouts/articles' %>
                <%= will_paginate @articles %>
              </div>
            </div>
            <div id="videos">
              <div id="test2" class="col s12">
                <%= render 'layouts/videos' %>
                <%= will_paginate @videos %>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="subscribe-container center" id="subscribe-page">
    <h5 id="subscribe-title">Enter your name and email to receive latest news</h5>
    <div class="col s12">
      <div class="row">
        <%= form_for :subscribe, url: subscribe_path do |f| %>
          <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <%= f.text_field :name %>
            <label for="icon_prefix">Full Name</label>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">email</i>
            <%= f.text_field :email %>
            <label for="icon_email">Email</label>
          </div>
          <%= f.submit 'Subscribe', class: "subscribe-button waves-effect waves-light btn-large" %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/static_pages/index.js.erb
$("#articles").html("<%= escape_javascript(render("layouts/articles")) %>");
$("#videos").html("<%= escape_javascript(render("layouts/videos")) %>");