config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'api_test' => 'api_test#test'

  root 'static_pages#index'

  resources :users
  resources :articles
  resources :videos

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'adminpanel' => 'adminpanel#index'
  post 'adminpanel' => 'adminpanel#new_resource'

  # subscribe route
  post 'subscribe' => 'static_pages#subscribe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/adminpanel_controller.rb
class AdminpanelController < ApplicationController
  #before_action :admin_user, only: [:index, :new_resource]

  def index
    @article_types = [
                        ['programming', 'programming'],['technical', 'technical'],['soft_skills', 'soft_skills'],['course', 'course'],
                        ['ruby', 'ruby'], ['web_development', 'web_development'], ['linux', 'linux'], ['database', 'database'], ['devops', 'devops'],
                        ['windows', 'windows']
                      ]
  end

  # action to add article or video
  def new_resource
    admin_redirect_link = '/adminpanel'

    @article = Article.new(article_params) unless params[:article].nil?
    @video = Video.new(video_params) unless params[:video].nil?
    if @video && @video.save
      flash[:success] = 'Video Added!'
      redirect_to admin_redirect_link
    elsif @article && @article.save
      flash[:success] = 'Article Added!'
      redirect_to admin_redirect_link
    else
      if !@article.nil?
        flash[:danger] = 'Not added!' + " " + @article.errors.full_messages
      elsif !@video.nil?
        flash[:danger] = 'Not added!' + " " + @video.errors.full_messages
      end
      redirect_to admin_redirect_link
    end
  end

private
  def article_params
    params.require(:article).permit(:title, :text, :article_type)
  end

  def video_params
    params.require(:video).permit(:title, :link, :video_type)
  end

  def admin_user
    redirect_to(root_url) && flash[:danger] = 'forbidden' unless current_user && current_user.admin?
  end
end

app/helpers/adminpanel_helper.rb
module AdminpanelHelper
end

app/views/adminpanel/index.html.erb
<%= render 'layouts/content_nav' %>
<%= link_to 'Logout', logout_path, :method => 'DELETE', class: "btn" %>
  <div class="row">
    <div class="col s5 forms">
      <a>Add Article</a>
      <%= form_for :article do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :text %>
        <%= f.text_area :text, class: 'new-resource-text-area' %>
        <%= f.label 'Article Type' %>
        <%= f.select :article_type, options_for_select(@article_types), {}, { :class => 'article-type-select' } %>
        <%= f.submit "Add Article", class: "btn" %>
      <% end %>
    </div>
    <div class="col s5 forms">
        <a>Add Video</a>
      <%= form_for :video do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :link %>
        <%= f.text_field :link %>
        <%= f.label :video_type %>
        <%= f.text_field :video_type %>
        <%= f.submit "Add Video", class: "btn" %>
      <% end %>
    </div>
  </div>