config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'api_test' => 'api_test#test'

  root 'static_pages#index'

  resources :users
  resources :articles
  resources :videos

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'adminpanel' => 'adminpanel#index'
  post 'adminpanel' => 'adminpanel#new_resource'

  # subscribe route
  post 'subscribe' => 'static_pages#subscribe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_articles.html.erb
<div class="main-page-feed-container">
  <div class="row">
    <% @articles.each do |article| %>
      <div class="col s4 main-page-media">
        <div class="article-logo">
          <%= link_to "railsbit.com", article_path(article) %>
        </div>
        <div class="article-title">
          <h6>
            <%= link_to "#{article.title}", article_path(article) %>
          </h6>
          <span class="article-signature"><%= article.created_at.strftime('%B') + " " + article.created_at.strftime('%d') + ", " + article.created_at.strftime('%G') + " / BY " + article.author_name.to_s %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_content_nav.html.erb
<nav>
  <div class="nav-wrapper theme-background-color darken-1">
    <a href="/" class="brand-logo center">railsbit</a>
    <ul id="nav-content" class="left hide-on-med-and-down">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Articles', articles_path %></a></li>
      <li><%= link_to 'Videos', videos_path %></li>
    </ul>
    <ul id="social-nav-icons" class="right hide-on-med-and-down">
      <li><a href="https://gitlab.com/mrjkc/railsbit.com" target="_blank"><i class="fa fa-gitlab fa-2x" title="Gitlab"></i></a></li>
      <li><a href="https://www.youtube.com/channel/UCFhi7a2IzvjnlgLoYiV0Pug/videos?view_as=subscriber" target="_blank"><i class="fa fa-youtube fa-2x" title="Youtube"></i></a></li>
      <li><a href="#" target="_blank"><i class="fa fa-facebook fa-2x" title="Facebook"></i></a></li>
      <li><a href="#" target="_blank"><i id="last-social-nav-icon" class="fa fa-twitter fa-2x" title="Twitter"></i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="page-footer theme-background-color darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">railsbit.com</h5>
        <p class="grey-text text-lighten-4">Your Number One Tech Blog <a href='#'>Contact Us</a></p>
      </div>
      <div class="col l4 offset-l2 s12">

      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2018 railsbit.com
    <a class="grey-text text-lighten-4 right" href="#!">Privacy Policy</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper theme-background-color darken-1">
    <a href="/" class="brand-logo center">railsbit</a>
    <ul id="nav-content" class="left hide-on-med-and-down">
      <li><a class="p2">Content</a></li>
      <li><a href="#">About</a></li>
      <li><a id="p3">Subscribe</a></li>
      <li><%= link_to 'Articles', articles_path %></li>
      <li><%= link_to 'Videos', videos_path %></li>
    </ul>
    <ul id="social-nav-icons" class="right hide-on-med-and-down">
      <li><a href="https://gitlab.com/mrjkc/railsbit.com" target="_blank"><i class="fa fa-gitlab fa-2x" title="Gitlab"></i></a></li>
      <li><a href="https://www.youtube.com/channel/UCFhi7a2IzvjnlgLoYiV0Pug/videos?view_as=subscriber" target="_blank"><i class="fa fa-youtube fa-2x" title="Youtube"></i></a></li>
      <li><a href="#" target="_blank"><i class="fa fa-facebook fa-2x" title="Facebook"></i></a></li>
      <li><a href="#" target="_blank"><i id="last-social-nav-icon" class="fa fa-twitter fa-2x" title="Twitter"></i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_videos.html.erb
<div class="main-page-feed-container">
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col s4 main-page-media">
        <iframe id="video"
          src=<%= "https://www.youtube.com/embed/#{video.link.split('=').last}" %> frameborder="0" allowfullscreen>
        </iframe>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsbit</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
  </head>

  <body id="body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
  </body>
</html>